
const employees = [
  {
    id: 1,
    password: "123",
    name: "John Smith",
    firstName: "John",
    email: "john.smith@example.com",
    taskNumbers: { active: 2, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        title: "Fix login bug",
        description: "Resolve the 500 error when users attempt to log in.",
        date: "2025-07-05",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Write unit tests",
        description: "Cover all components with Jest tests.",
        date: "2025-07-02",
        category: "QA",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Database backup",
        description: "Perform a scheduled backup of the production database.",
        date: "2025-07-01",
        category: "Operations",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Sprint planning",
        description: "Prepare notes for sprint planning with PM.",
        date: "2025-07-06",
        category: "Meeting",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    password: "123",
    name: "Sarah Johnson",
    firstName: "Sarah",
    email: "sarah.johnson@example.com",
    taskNumbers: { active: 2, newTask: 1, completed: 1, failed: 0 },
    tasks: [
      {
        title: "Create wireframes",
        description: "Design wireframes for the new user dashboard.",
        date: "2025-07-03",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client call",
        description: "Discuss feedback with client via Zoom.",
        date: "2025-07-04",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Review PRs",
        description: "Check pull requests for the UI improvements branch.",
        date: "2025-07-06",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    password: "123",
    name: "Robert Brown",
    firstName: "Robert",
    email: "robert.brown@example.com",
    taskNumbers: { active: 2, newTask: 2, completed: 2, failed: 1 },
    tasks: [
      {
        title: "API testing",
        description: "Test all endpoints with Postman and report issues.",
        date: "2025-07-02",
        category: "QA",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Deployment",
        description: "Deploy the latest build to staging.",
        date: "2025-07-05",
        category: "Operations",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Write documentation",
        description: "Update the API documentation for v2 endpoints.",
        date: "2025-07-06",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Code Review",
        description: "Review code for the new payment integration module.",
        date: "2025-07-07",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Security audit",
        description: "Run security checks for user input fields.",
        date: "2025-07-03",
        category: "Security",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    password: "123",
    name: "Emily Davis",
    firstName: "Emily",
    email: "emily.davis@example.com",
    taskNumbers: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        title: "Marketing campaign",
        description: "Plan the summer social media campaign.",
        date: "2025-07-01",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Customer survey",
        description: "Design and distribute Q3 customer satisfaction survey.",
        date: "2025-07-04",
        category: "Research",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Blog post",
        description: "Write blog content on latest product features.",
        date: "2025-07-06",
        category: "Content",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    password: "123",
    name: "Michael Wilson",
    firstName: "Michael",
    email: "michael.wilson@example.com",
    taskNumbers: { active: 3, newTask: 2, completed: 2, failed: 0 },
    tasks: [
      {
        title: "Performance review",
        description: "Conduct performance evaluations for team members.",
        date: "2025-07-05",
        category: "HR",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Team onboarding",
        description: "Onboard two new engineers to the backend team.",
        date: "2025-07-03",
        category: "HR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Budget report",
        description: "Submit Q2 budget analysis to finance department.",
        date: "2025-07-02",
        category: "Finance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Weekly sync",
        description: "Attend leadership sync and align goals.",
        date: "2025-07-01",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update team OKRs",
        description: "Revise and publish updated team OKRs for Q3.",
        date: "2025-07-07",
        category: "Planning",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];


const admin = [
  {
    id: 1,
    password: "123",
    name: "Sid",
    email: "sid@gmail.com",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return{employees,admin}
};
